import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { getMcpAuthContext } from "agents/mcp";
import { z } from "zod";
import { eq, and } from "drizzle-orm";
import { pet as petTable, story as storyTable } from "@repo/db/schema";
import { getDb } from "../../db";

function getPlayerId(): string {
  const ctx = getMcpAuthContext();
  const userId = ctx?.props?.userId as string | undefined;
  if (!userId) {
    throw new Error("Not authenticated");
  }
  return userId;
}

function errorResult(message: string) {
  return {
    content: [{ type: "text" as const, text: JSON.stringify({ error: message }) }],
    isError: true as const,
  };
}

function validateAsciiArt(asciiArt: string): string | null {
  const lines = asciiArt.split("\n");
  if (lines.length > 6) {
    return "ASCII art must be at most 6 lines.";
  }
  if (lines.some((line) => line.length > 20)) {
    return "ASCII art must be at most 20 characters wide.";
  }
  return null;
}

export function registerSaveStoryTool(server: McpServer, env: CloudflareBindings) {
  server.registerTool(
    "save-story",
    {
      description: "Save client-generated narratives for story events, or save ASCII art for your pet. Called after the client LLM narrates events from `feed` or generates art from `adopt`.",
      inputSchema: {
        stories: z
          .array(
            z.object({
              id: z.string().describe("Story event ID from feed response"),
              narrative: z.string().describe("The narrative text generated by the client LLM"),
            })
          )
          .optional()
          .describe("Story narratives to save"),
        petId: z.string().optional().describe("Pet ID — required when saving ASCII art"),
        asciiArt: z.string().optional().describe("ASCII art for the pet (generated at adoption)"),
      },
    },
    async ({ stories, petId, asciiArt }) => {
      try {
        const playerId = getPlayerId();
        const db = getDb(env);

        const pets = await db
          .select({ id: petTable.id })
          .from(petTable)
          .where(eq(petTable.playerId, playerId))
          .limit(1);

        if (pets.length === 0) {
          return errorResult("You don't have a pet yet!");
        }

        const ownedPetId = pets[0].id;
        let savedCount = 0;
        let savedStoriesCount = 0;

        if ((asciiArt && !petId) || (!asciiArt && petId)) {
          return errorResult("Provide both petId and asciiArt together.");
        }

        if (asciiArt && petId) {
          if (petId !== ownedPetId) {
            return errorResult("That's not your pet.");
          }

          const validationError = validateAsciiArt(asciiArt);
          if (validationError) {
            return errorResult(validationError);
          }

          const petRows = await db
            .select({ asciiArt: petTable.asciiArt })
            .from(petTable)
            .where(eq(petTable.id, ownedPetId))
            .limit(1);

          if (petRows[0]?.asciiArt) {
            return errorResult("ASCII art has already been saved for this pet.");
          }

          await db
            .update(petTable)
            .set({ asciiArt })
            .where(eq(petTable.id, ownedPetId));
          savedCount++;
        }

        if (stories && stories.length > 0) {
          for (const story of stories) {
            const matching = await db
              .select({ id: storyTable.id })
              .from(storyTable)
              .where(and(eq(storyTable.id, story.id), eq(storyTable.petId, ownedPetId)))
              .limit(1);

            if (matching.length === 0) {
              continue;
            }

            await db
              .update(storyTable)
              .set({ story: story.narrative })
              .where(and(eq(storyTable.id, story.id), eq(storyTable.petId, ownedPetId)));
            savedCount++;
            savedStoriesCount++;
          }
        }

        if (savedCount === 0) {
          return {
            content: [
              {
                type: "text" as const,
                text: "Nothing to save. Provide stories or asciiArt.",
              },
            ],
          };
        }

        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify({
                saved: savedCount,
                asciiArt: !!asciiArt,
                stories: savedStoriesCount,
              }),
            },
          ],
        };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return errorResult(message);
      }
    }
  );
}
